require ("util")
require ("circuit-connector-sprites")
local hit_effects = require("__base__.prototypes.entity.hit-effects")
local sounds = require("__base__.prototypes.entity.sounds")

entities_icons_path = "__Belts_Pro__/graphics/icons/belts/"
entities_path = "__Belts_Pro__/graphics/entity/belts/"
remnants_path = "__Belts_Pro__/graphics/remnants/"

data:extend({
  {
    type = "splitter",
    name = "advanced-splitter",
    localised_description = { "entity-description.splitter" },
    icon = entities_icons_path .. "advanced-splitter.png",
    icon_size = 64,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 0.2, result = "advanced-splitter" },
    max_health = 250,
    corpse = "advanced-splitter-remnant",
    resistances = {
      {
        type = "fire",
        percent = 50,
      },
    },
    collision_box = { { -0.9, -0.4 }, { 0.9, 0.4 } },
    selection_box = { { -0.9, -0.5 }, { 0.9, 0.5 } },
    structure_animation_speed_coefficient = 1.2,
    structure_animation_movement_cooldown = 10,
    belt_animation_set = advanced_transport_belt_animation_set,
    fast_replaceable_group = "transport-belt",
    next_upgrade = "superior-splitter",
    speed = 0.125,
    working_sound = sounds.express_splitter,
    related_transport_belt = "advanced-transport-belt",
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
    animation_speed_coefficient = 28,
    structure = {
      north = 
      util.sprite_load(entities_path .. "advanced-splitter-north",
        {
          frame_count = 32,
          priority = "extra-high",
	        scale = 0.5,
        }
      ),
      east = {
        filename = entities_path .. "advanced-splitter-east.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 84,
        shift = util.by_pixel(4, 13),
        scale = 0.5,
      },
      south = {
        filename = entities_path .. "advanced-splitter-south.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 164,
        height = 64,
        shift = util.by_pixel(4, 0),
        scale = 0.5,
      },
      west = {
        filename = entities_path .. "advanced-splitter-west.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 86,
        shift = util.by_pixel(6, 12),
        scale = 0.5,
      },
    },
    structure_patch = {
      north = util.empty_sprite(),
      east = {
        filename = entities_path
          .. "advanced-splitter-east-top_patch.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 104,
        shift = util.by_pixel(4, -20),
        scale = 0.5,
      },
      south = util.empty_sprite(),
      west = {
        filename = entities_path
          .. "advanced-splitter-west-top_patch.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 96,
        shift = util.by_pixel(6, -18),
        scale = 0.5,
      },
    },
    circuit_wire_max_distance = splitter_circuit_wire_max_distance,
    circuit_connector = circuit_connector_definitions["splitter"],
    default_input_left_condition = { first = {type="virtual", name="signal-I"}, comparator="<", second=0},
    default_input_right_condition = { first = {type="virtual", name="signal-I"}, comparator=">", second=0},
    default_output_left_condition = { first = {type="virtual", name="signal-O"}, comparator="<", second=0},
    default_output_right_condition = { first = {type="virtual", name="signal-O"}, comparator=">", second=0},
  },
  {
    type = "transport-belt",
    name = "advanced-transport-belt",
    icon = entities_icons_path .. "advanced-transport-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 0.2, result = "advanced-transport-belt" },
    max_health = 200,
    corpse = "advanced-transport-belt-remnant",
    resistances = {
      {
        type = "fire",
        percent = 50,
      },
    },
    collision_box = { { -0.4, -0.4 }, { 0.4, 0.4 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    damaged_trigger_effect = hit_effects.entity(),
    open_sound = sounds.transport_belt_open,
    close_sound = sounds.transport_belt_close,
    working_sound = {
      sound = {
        filename = "__base__/sound/express-transport-belt.ogg",
        volume = 0.4,
      },
      persistent = true,
      use_doppler_shift = false
    },
    animations = {
      filename = entities_path
        .. "advanced-transport-belt.png",
      priority = "extra-high",
      width = 128,
      height = 128,
      frame_count = 32,
      direction_count = 12,
      scale = 0.5,
    },
    belt_animation_set = advanced_transport_belt_animation_set,
    fast_replaceable_group = "transport-belt",
    next_upgrade = "superior-transport-belt",
    related_underground_belt = "advanced-underground-belt",
    speed = 0.125,
    animation_speed_coefficient = 32,
    connector_frame_sprites = transport_belt_connector_frame_sprites,
    circuit_connector = circuit_connector_definitions["belt"],
    circuit_wire_max_distance = transport_belt_circuit_wire_max_distance,
  },
  {
    type = "underground-belt",
    name = "advanced-underground-belt",
    icon = entities_icons_path .. "advanced-underground-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 0.2, result = "advanced-underground-belt" },
    max_health = 200,
    corpse = "advanced-underground-belt-remnant",
    max_distance = 21,
    underground_sprite = {
      filename = "__core__/graphics/arrows/underground-lines.png",
      priority = "high",
      width = 64,
      height = 64,
      x = 64,
      scale = 0.5,
    },
    underground_remove_belts_sprite = {
      filename = "__core__/graphics/arrows/underground-lines-remove.png",
      priority = "high",
      width = 64,
      height = 64,
      x = 64,
      scale = 0.5,
    },
    resistances = {
      {
        type = "fire",
        percent = 50,
      },
      {
        type = "impact",
        percent = 30,
      },
    },
    collision_box = { { -0.4, -0.4 }, { 0.4, 0.4 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    damaged_trigger_effect = hit_effects.entity(),
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
    working_sound =
    {
      sound = {filename = "__base__/sound/express-underground-belt.ogg", volume = 0.35, audible_distance_modifier = 0.5},
      max_sounds_per_prototype = 2,
      persistent = true,
      use_doppler_shift = false
    },
    belt_animation_set = advanced_transport_belt_animation_set,
    fast_replaceable_group = "transport-belt",
    next_upgrade = "superior-underground-belt",
    speed = 0.125,
    animation_speed_coefficient = 28,
    structure = {
      direction_in = {
        sheet = {
          filename = entities_path
            .. "advanced-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192,
          scale = 0.5,
        },
      },
      direction_out = {
        sheet = {
          filename = entities_path
            .. "advanced-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
      direction_in_side_loading = {
        sheet = {
          filename = entities_path
            .. "advanced-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192 * 3,
          scale = 0.5,
        },
      },
      direction_out_side_loading = {
        sheet = {
          filename = entities_path
            .. "advanced-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192 * 2,
          scale = 0.5,
        },
      },
      back_patch = {
        sheet = {
          filename = entities_path
            .. "advanced-underground-belt-structure-back-patch.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
      front_patch = {
        sheet = {
          filename = entities_path
            .. "advanced-underground-belt-structure-front-patch.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
    },
  },
  {
    type = "corpse",
    name = "advanced-splitter-remnant",
    localised_name = { "remnant-name", { "entity-name.advanced-splitter" } },
    icon = entities_icons_path .. "advanced-splitter.png",
    icon_size = 64,
    flags = { "placeable-neutral", "not-on-map" },
    selection_box = { { -0.9, -0.5 }, { 0.9, 0.5 } },
    tile_width = 2,
    tile_height = 1,
    selectable_in_game = false,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    time_before_removed = 60 * 60 * 15, -- 15 minutes
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = {
      filename = remnants_path .. "advanced-splitter-remnant.png",
      line_length = 1,
      width = 172,
      height = 156,
      frame_count = 1,
      variation_count = 1,
      axially_symmetrical = false,
      direction_count = 4,
      shift = util.by_pixel(1, 3),
      scale = 0.5,
    },
  },
  {
    type = "corpse",
    name = "advanced-transport-belt-remnant",
    localised_name = { "remnant-name", { "entity-name.advanced-transport-belt" } },
    icon = entities_icons_path .. "advanced-transport-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "not-on-map" },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    tile_width = 1,
    tile_height = 1,
    selectable_in_game = false,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    time_before_removed = 60 * 60 * 15, -- 15 minutes
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = make_rotated_animation_variations_from_sheet(8, {
      filename = remnants_path
        .. "advanced-transport-belt-remnant.png",
      line_length = 1,
      width = 106,
      height = 102,
      frame_count = 1,
      variation_count = 1,
      axially_symmetrical = false,
      direction_count = 1,
      shift = util.by_pixel(1, -0.5),
      scale = 0.5,
    }),
  },
  {
    type = "corpse",
    name = "advanced-underground-belt-remnant",
    localised_name = { "remnant-name", { "entity-name.advanced-underground-belt" } },
    icon = entities_icons_path .. "advanced-underground-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "not-on-map", "building-direction-8-way" },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    tile_width = 1,
    tile_height = 1,
    selectable_in_game = false,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    time_before_removed = 60 * 60 * 15, -- 15 minutes
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = {
      filename = remnants_path
        .. "advanced-underground-belt-remnant.png",
      line_length = 1,
      width = 116,
      height = 100,
      frame_count = 1,
      variation_count = 1,
      axially_symmetrical = false,
      direction_count = 8,
      shift = util.by_pixel(3.5, 3.5),
      scale = 0.5,
    },
  },
  -- Superior
  {
    type = "splitter",
    name = "superior-splitter",
    localised_description = { "entity-description.splitter" },
    icon = entities_icons_path .. "superior-splitter.png",
    icon_size = 64,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 0.2, result = "superior-splitter" },
    max_health = 250,
    corpse = "superior-splitter-remnant",
    resistances = {
      {
        type = "fire",
        percent = 50,
      },
    },
    collision_box = { { -0.9, -0.4 }, { 0.9, 0.4 } },
    selection_box = { { -0.9, -0.5 }, { 0.9, 0.5 } },
    structure_animation_speed_coefficient = 1.2,
    structure_animation_movement_cooldown = 10,
    belt_animation_set = superior_transport_belt_animation_set,
    fast_replaceable_group = "transport-belt",
    next_upgrade = "ultrasuperior-splitter",
    speed = 0.1875,
    working_sound = sounds.express_splitter,
    related_transport_belt = "superior-transport-belt",
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
    animation_speed_coefficient = 30,
    structure = {
      north = {
        filename = entities_path .. "superior-splitter-north.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 160,
        height = 70,
        shift = util.by_pixel(7, 0),
        scale = 0.5,
      },
      east = {
        filename = entities_path .. "superior-splitter-east.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 84,
        shift = util.by_pixel(4, 13),
        scale = 0.5,
      },
      south = {
        filename = entities_path .. "superior-splitter-south.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 164,
        height = 64,
        shift = util.by_pixel(4, 0),
        scale = 0.5,
      },
      west = {
        filename = entities_path .. "superior-splitter-west.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 86,
        shift = util.by_pixel(6, 12),
        scale = 0.5,
      },
    },
    structure_patch = {
      north = util.empty_sprite(),
      east = {
        filename = entities_path
          .. "superior-splitter-east-top_patch.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 104,
        shift = util.by_pixel(4, -20),
        scale = 0.5,
      },
      south = util.empty_sprite(),
      west = {
        filename = entities_path
          .. "superior-splitter-west-top_patch.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 96,
        shift = util.by_pixel(6, -18),
        scale = 0.5,
      },
    },
    circuit_wire_max_distance = splitter_circuit_wire_max_distance,
    circuit_connector = circuit_connector_definitions["splitter"],
    default_input_left_condition = { first = {type="virtual", name="signal-I"}, comparator="<", second=0},
    default_input_right_condition = { first = {type="virtual", name="signal-I"}, comparator=">", second=0},
    default_output_left_condition = { first = {type="virtual", name="signal-O"}, comparator="<", second=0},
    default_output_right_condition = { first = {type="virtual", name="signal-O"}, comparator=">", second=0},
  },
  {
    type = "transport-belt",
    name = "superior-transport-belt",
    icon = entities_icons_path .. "superior-transport-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 0.2, result = "superior-transport-belt" },
    max_health = 200,
    corpse = "superior-transport-belt-remnant",
    resistances = {
      {
        type = "fire",
        percent = 50,
      },
    },
    collision_box = { { -0.4, -0.4 }, { 0.4, 0.4 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    damaged_trigger_effect = hit_effects.entity(),
    open_sound = sounds.transport_belt_open,
    close_sound = sounds.transport_belt_close,
    working_sound = {
      sound = {
        filename = "__base__/sound/transport-belt.ogg",
        volume = 0.4,
      },
      persistent = true,
    },
    animations = {
      filename = entities_path
        .. "superior-transport-belt.png",
      priority = "extra-high",
      width = 128,
      height = 128,
      frame_count = 32,
      direction_count = 12,
      scale = 0.5,
    },
    belt_animation_set = superior_transport_belt_animation_set,
    fast_replaceable_group = "transport-belt",
    related_underground_belt = "superior-underground-belt",
    next_upgrade = "ultrasuperior-transport-belt",
    speed = 0.1875,
    animation_speed_coefficient = 32,
    connector_frame_sprites = transport_belt_connector_frame_sprites,
    circuit_wire_connection_points = circuit_connector_definitions["belt"].points,
    circuit_connector_sprites = circuit_connector_definitions["belt"].sprites,
    circuit_wire_max_distance = transport_belt_circuit_wire_max_distance,
  },
  {
    type = "underground-belt",
    name = "superior-underground-belt",
    icon = entities_icons_path .. "superior-underground-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 0.2, result = "superior-underground-belt" },
    max_health = 200,
    corpse = "superior-underground-belt-remnant",
    max_distance = 25,
    underground_sprite = {
      filename = "__core__/graphics/arrows/underground-lines.png",
      priority = "high",
      width = 64,
      height = 64,
      x = 64,
      scale = 0.5,
    },
    underground_remove_belts_sprite = {
      filename = "__core__/graphics/arrows/underground-lines-remove.png",
      priority = "high",
      width = 64,
      height = 64,
      x = 64,
      scale = 0.5,
    },
    resistances = {
      {
        type = "fire",
        percent = 50,
      },
      {
        type = "impact",
        percent = 30,
      },
    },
    collision_box = { { -0.4, -0.4 }, { 0.4, 0.4 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    underground_collision_mask = {layers={lava_tile=true, empty_space=true}},
    damaged_trigger_effect = hit_effects.entity(),
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
    working_sound =
    {
      sound = {filename = "__base__/sound/express-underground-belt.ogg", volume = 0.35, audible_distance_modifier = 0.5},
      max_sounds_per_prototype = 2,
      persistent = true,
      use_doppler_shift = false
    },
    belt_animation_set = superior_transport_belt_animation_set,
    fast_replaceable_group = "transport-belt",
    next_upgrade = "ultrasuperior-underground-belt",
    speed = 0.1875,
    animation_speed_coefficient = 30,
    structure = {
      direction_in = {
        sheet = {
          filename = entities_path
            .. "superior-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192,
          scale = 0.5,
        },
      },
      direction_out = {
        sheet = {
          filename = entities_path
            .. "superior-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
      direction_in_side_loading = {
        sheet = {
          filename = entities_path
            .. "superior-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192 * 3,
          scale = 0.5,
        },
      },
      direction_out_side_loading = {
        sheet = {
          filename = entities_path
            .. "superior-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192 * 2,
          scale = 0.5,
        },
      },
      back_patch = {
        sheet = {
          filename = entities_path
            .. "superior-underground-belt-structure-back-patch.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
      front_patch = {
        sheet = {
          filename = entities_path
            .. "superior-underground-belt-structure-front-patch.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
    },
  },

  {
    type = "corpse",
    name = "superior-splitter-remnant",
    localised_name = { "remnant-name", { "entity-name.superior-splitter" } },
    icon = entities_icons_path .. "superior-splitter.png",
    icon_size = 64,
    flags = { "placeable-neutral", "not-on-map" },
    selection_box = { { -0.9, -0.5 }, { 0.9, 0.5 } },
    tile_width = 2,
    tile_height = 1,
    selectable_in_game = false,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    time_before_removed = 60 * 60 * 15, -- 15 minutes
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = {
      filename = remnants_path .. "superior-splitter-remnant.png",
      line_length = 1,
      width = 172,
      height = 156,
      frame_count = 1,
      variation_count = 1,
      axially_symmetrical = false,
      direction_count = 4,
      shift = util.by_pixel(1, 3),
      scale = 0.5,
    },
  },
  {
    type = "corpse",
    name = "superior-transport-belt-remnant",
    localised_name = { "remnant-name", { "entity-name.superior-transport-belt" } },
    icon = entities_icons_path .. "superior-transport-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "not-on-map" },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    tile_width = 1,
    tile_height = 1,
    selectable_in_game = false,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    time_before_removed = 60 * 60 * 15, -- 15 minutes
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = make_rotated_animation_variations_from_sheet(8, {
      filename = remnants_path
        .. "superior-transport-belt-remnant.png",
      line_length = 1,
      width = 106,
      height = 102,
      frame_count = 1,
      variation_count = 1,
      axially_symmetrical = false,
      direction_count = 1,
      shift = util.by_pixel(1, -0.5),
      scale = 0.5,
    }),
  },
  {
    type = "corpse",
    name = "superior-underground-belt-remnant",
    localised_name = { "remnant-name", { "entity-name.superior-underground-belt" } },
    icon = entities_icons_path .. "superior-underground-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "not-on-map", "building-direction-8-way" },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    tile_width = 1,
    tile_height = 1,
    selectable_in_game = false,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    time_before_removed = 60 * 60 * 15, -- 15 minutes
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = {
      filename = remnants_path
        .. "superior-underground-belt-remnant.png",
      line_length = 1,
      width = 116,
      height = 100,
      frame_count = 1,
      variation_count = 1,
      axially_symmetrical = false,
      direction_count = 8,
      shift = util.by_pixel(3.5, 3.5),
      scale = 0.5,
    },
  },
  -- Ultrasuperior
  {
    type = "splitter",
    name = "ultrasuperior-splitter",
    localised_description = { "entity-description.splitter" },
    icon = entities_icons_path .. "ultrasuperior-splitter.png",
    icon_size = 64,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 0.2, result = "ultrasuperior-splitter" },
    max_health = 250,
    corpse = "ultrasuperior-splitter-remnant",
    resistances = {
      {
        type = "fire",
        percent = 50,
      },
    },
    collision_box = { { -0.9, -0.4 }, { 0.9, 0.4 } },
    selection_box = { { -0.9, -0.5 }, { 0.9, 0.5 } },
    structure_animation_speed_coefficient = 1.2,
    structure_animation_movement_cooldown = 10,
    belt_animation_set = ultrasuperior_transport_belt_animation_set,
    fast_replaceable_group = "transport-belt",
    speed = 0.375,
    working_sound = sounds.express_splitter,
    related_transport_belt = "ultrasuperior-transport-belt",
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
    animation_speed_coefficient = 30,
    structure = {
      north = {
        filename = entities_path .. "ultrasuperior-splitter-north.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 160,
        height = 70,
        shift = util.by_pixel(7, 0),
        scale = 0.5,
      },
      east = {
        filename = entities_path .. "ultrasuperior-splitter-east.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 84,
        shift = util.by_pixel(4, 13),
        scale = 0.5,
      },
      south = {
        filename = entities_path .. "ultrasuperior-splitter-south.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 164,
        height = 64,
        shift = util.by_pixel(4, 0),
        scale = 0.5,
      },
      west = {
        filename = entities_path .. "ultrasuperior-splitter-west.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 86,
        shift = util.by_pixel(6, 12),
        scale = 0.5,
      },
    },
    structure_patch = {
      north = util.empty_sprite(),
      east = {
        filename = entities_path
          .. "ultrasuperior-splitter-east-top_patch.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 104,
        shift = util.by_pixel(4, -20),
        scale = 0.5,
      },
      south = util.empty_sprite(),
      west = {
        filename = entities_path
          .. "ultrasuperior-splitter-west-top_patch.png",
        frame_count = 32,
        line_length = 8,
        priority = "extra-high",
        width = 90,
        height = 96,
        shift = util.by_pixel(6, -18),
        scale = 0.5,
      },
    },
    circuit_wire_max_distance = splitter_circuit_wire_max_distance,
    circuit_connector = circuit_connector_definitions["splitter"],
    default_input_left_condition = { first = {type="virtual", name="signal-I"}, comparator="<", second=0},
    default_input_right_condition = { first = {type="virtual", name="signal-I"}, comparator=">", second=0},
    default_output_left_condition = { first = {type="virtual", name="signal-O"}, comparator="<", second=0},
    default_output_right_condition = { first = {type="virtual", name="signal-O"}, comparator=">", second=0},
  },
  {
    type = "transport-belt",
    name = "ultrasuperior-transport-belt",
    icon = entities_icons_path .. "ultrasuperior-transport-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 0.2, result = "ultrasuperior-transport-belt" },
    max_health = 200,
    corpse = "ultrasuperior-transport-belt-remnant",
    resistances = {
      {
        type = "fire",
        percent = 50,
      },
    },
    collision_box = { { -0.4, -0.4 }, { 0.4, 0.4 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    damaged_trigger_effect = hit_effects.entity(),
    open_sound = sounds.transport_belt_open,
    close_sound = sounds.transport_belt_close,
    working_sound = {
      sound = {
        filename = "__base__/sound/transport-belt.ogg",
        volume = 0.4,
      },
      persistent = true,
    },
    animations = {
      filename = entities_path
        .. "ultrasuperior-transport-belt.png",
      priority = "extra-high",
      width = 128,
      height = 128,
      frame_count = 32,
      direction_count = 12,
      scale = 0.5,
    },
    belt_animation_set = ultrasuperior_transport_belt_animation_set,
    fast_replaceable_group = "transport-belt",
    related_underground_belt = "ultrasuperior-underground-belt",
    speed = 0.375,
    animation_speed_coefficient = 32,
    connector_frame_sprites = transport_belt_connector_frame_sprites,
    circuit_wire_connection_points = circuit_connector_definitions["belt"].points,
    circuit_connector_sprites = circuit_connector_definitions["belt"].sprites,
    circuit_wire_max_distance = transport_belt_circuit_wire_max_distance,
  },
  {
    type = "underground-belt",
    name = "ultrasuperior-underground-belt",
    icon = entities_icons_path .. "ultrasuperior-underground-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 0.2, result = "ultrasuperior-underground-belt" },
    max_health = 200,
    corpse = "ultrasuperior-underground-belt-remnant",
    max_distance = 29,
    underground_sprite = {
      filename = "__core__/graphics/arrows/underground-lines.png",
      priority = "high",
      width = 64,
      height = 64,
      x = 64,
      scale = 0.5,
    },
    underground_remove_belts_sprite = {
      filename = "__core__/graphics/arrows/underground-lines-remove.png",
      priority = "high",
      width = 64,
      height = 64,
      x = 64,
      scale = 0.5,
    },
    resistances = {
      {
        type = "fire",
        percent = 50,
      },
      {
        type = "impact",
        percent = 30,
      },
    },
    collision_box = { { -0.4, -0.4 }, { 0.4, 0.4 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    underground_collision_mask = {layers={lava_tile=true, empty_space=true}},
    damaged_trigger_effect = hit_effects.entity(),
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
    working_sound =
    {
      sound = {filename = "__base__/sound/express-underground-belt.ogg", volume = 0.35, audible_distance_modifier = 0.5},
      max_sounds_per_prototype = 2,
      persistent = true,
      use_doppler_shift = false
    },
    belt_animation_set = ultrasuperior_transport_belt_animation_set,
    fast_replaceable_group = "transport-belt",
    speed = 0.375,
    animation_speed_coefficient = 30,
    structure = {
      direction_in = {
        sheet = {
          filename = entities_path
            .. "ultrasuperior-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192,
          scale = 0.5,
        },
      },
      direction_out = {
        sheet = {
          filename = entities_path
            .. "ultrasuperior-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
      direction_in_side_loading = {
        sheet = {
          filename = entities_path
            .. "ultrasuperior-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192 * 3,
          scale = 0.5,
        },
      },
      direction_out_side_loading = {
        sheet = {
          filename = entities_path
            .. "ultrasuperior-underground-belt-structure.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          y = 192 * 2,
          scale = 0.5,
        },
      },
      back_patch = {
        sheet = {
          filename = entities_path
            .. "ultrasuperior-underground-belt-structure-back-patch.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
      front_patch = {
        sheet = {
          filename = entities_path
            .. "ultrasuperior-underground-belt-structure-front-patch.png",
          priority = "extra-high",
          width = 192,
          height = 192,
          scale = 0.5,
        },
      },
    },
  },
  {
    type = "corpse",
    name = "ultrasuperior-splitter-remnant",
    localised_name = { "remnant-name", { "entity-name.ultrasuperior-splitter" } },
    icon = entities_icons_path .. "ultrasuperior-splitter.png",
    icon_size = 64,
    flags = { "placeable-neutral", "not-on-map" },
    selection_box = { { -0.9, -0.5 }, { 0.9, 0.5 } },
    tile_width = 2,
    tile_height = 1,
    selectable_in_game = false,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    time_before_removed = 60 * 60 * 15, -- 15 minutes
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = {
      filename = remnants_path .. "ultrasuperior-splitter-remnant.png",
      line_length = 1,
      width = 172,
      height = 156,
      frame_count = 1,
      variation_count = 1,
      axially_symmetrical = false,
      direction_count = 4,
      shift = util.by_pixel(1, 3),
      scale = 0.5,
    },
  },
  {
    type = "corpse",
    name = "ultrasuperior-transport-belt-remnant",
    localised_name = { "remnant-name", { "entity-name.ultrasuperior-transport-belt" } },
    icon = entities_icons_path .. "ultrasuperior-transport-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "not-on-map" },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    tile_width = 1,
    tile_height = 1,
    selectable_in_game = false,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    time_before_removed = 60 * 60 * 15, -- 15 minutes
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = make_rotated_animation_variations_from_sheet(8, {
      filename = remnants_path
        .. "ultrasuperior-transport-belt-remnant.png",
      line_length = 1,
      width = 106,
      height = 102,
      frame_count = 1,
      variation_count = 1,
      axially_symmetrical = false,
      direction_count = 1,
      shift = util.by_pixel(1, -0.5),
      scale = 0.5,
    }),
  },
  {
    type = "corpse",
    name = "ultrasuperior-underground-belt-remnant",
    localised_name = { "remnant-name", { "entity-name.ultrasuperior-underground-belt" } },
    icon = entities_icons_path .. "ultrasuperior-underground-belt.png",
    icon_size = 64,
    flags = { "placeable-neutral", "not-on-map", "building-direction-8-way" },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    tile_width = 1,
    tile_height = 1,
    selectable_in_game = false,
    subgroup = "remnants",
    order = "d[remnants]-a[generic]-a[small]",
    time_before_removed = 60 * 60 * 15, -- 15 minutes
    final_render_layer = "remnants",
    remove_on_tile_placement = false,
    animation = {
      filename = remnants_path
        .. "ultrasuperior-underground-belt-remnant.png",
      line_length = 1,
      width = 116,
      height = 100,
      frame_count = 1,
      variation_count = 1,
      axially_symmetrical = false,
      direction_count = 8,
      shift = util.by_pixel(3.5, 3.5),
      scale = 0.5,
    },
  },
})
